// flow-typed signature: 57d44ddcfda954bfec4df9fdfe828b5b
// flow-typed version: <<STUB>>/d3-selection-multi_v^1.0.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-selection-multi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-selection-multi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-selection-multi/build/d3-selection-multi' {
  declare module.exports: any;
}

declare module 'd3-selection-multi/build/d3-selection-multi.min' {
  declare module.exports: any;
}

declare module 'd3-selection-multi/src/selection/attrs' {
  declare module.exports: any;
}

declare module 'd3-selection-multi/src/selection/properties' {
  declare module.exports: any;
}

declare module 'd3-selection-multi/src/selection/styles' {
  declare module.exports: any;
}

declare module 'd3-selection-multi/src/transition/attrs' {
  declare module.exports: any;
}

declare module 'd3-selection-multi/src/transition/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-selection-multi/build/d3-selection-multi.js' {
  declare module.exports: $Exports<'d3-selection-multi/build/d3-selection-multi'>;
}
declare module 'd3-selection-multi/build/d3-selection-multi.min.js' {
  declare module.exports: $Exports<'d3-selection-multi/build/d3-selection-multi.min'>;
}
declare module 'd3-selection-multi/index' {
  declare module.exports: $Exports<'d3-selection-multi'>;
}
declare module 'd3-selection-multi/index.js' {
  declare module.exports: $Exports<'d3-selection-multi'>;
}
declare module 'd3-selection-multi/src/selection/attrs.js' {
  declare module.exports: $Exports<'d3-selection-multi/src/selection/attrs'>;
}
declare module 'd3-selection-multi/src/selection/properties.js' {
  declare module.exports: $Exports<'d3-selection-multi/src/selection/properties'>;
}
declare module 'd3-selection-multi/src/selection/styles.js' {
  declare module.exports: $Exports<'d3-selection-multi/src/selection/styles'>;
}
declare module 'd3-selection-multi/src/transition/attrs.js' {
  declare module.exports: $Exports<'d3-selection-multi/src/transition/attrs'>;
}
declare module 'd3-selection-multi/src/transition/styles.js' {
  declare module.exports: $Exports<'d3-selection-multi/src/transition/styles'>;
}
