// flow-typed signature: ea53f17a2137d09c14e064030ef7b719
// flow-typed version: <<STUB>>/@babel/plugin-transform-spread_v^7.2.2/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-spread'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-spread' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-spread/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-spread/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-spread/lib'>;
}
declare module '@babel/plugin-transform-spread/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-spread/lib'>;
}
