// flow-typed signature: d80dc3ef2f8c9242443b4b7536871ea4
// flow-typed version: <<STUB>>/d3-axis_v1.0.12/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-axis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-axis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-axis/dist/d3-axis' {
  declare module.exports: any;
}

declare module 'd3-axis/dist/d3-axis.min' {
  declare module.exports: any;
}

declare module 'd3-axis/rollup.config' {
  declare module.exports: any;
}

declare module 'd3-axis/src/array' {
  declare module.exports: any;
}

declare module 'd3-axis/src/axis' {
  declare module.exports: any;
}

declare module 'd3-axis/src/identity' {
  declare module.exports: any;
}

declare module 'd3-axis/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-axis/dist/d3-axis.js' {
  declare module.exports: $Exports<'d3-axis/dist/d3-axis'>;
}
declare module 'd3-axis/dist/d3-axis.min.js' {
  declare module.exports: $Exports<'d3-axis/dist/d3-axis.min'>;
}
declare module 'd3-axis/rollup.config.js' {
  declare module.exports: $Exports<'d3-axis/rollup.config'>;
}
declare module 'd3-axis/src/array.js' {
  declare module.exports: $Exports<'d3-axis/src/array'>;
}
declare module 'd3-axis/src/axis.js' {
  declare module.exports: $Exports<'d3-axis/src/axis'>;
}
declare module 'd3-axis/src/identity.js' {
  declare module.exports: $Exports<'d3-axis/src/identity'>;
}
declare module 'd3-axis/src/index' {
  declare module.exports: $Exports<'d3-axis/src'>;
}
declare module 'd3-axis/src/index.js' {
  declare module.exports: $Exports<'d3-axis/src'>;
}
